// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyARltQLFudCyPx7gF5aez2n25nSaL-IBLs',
    appId: '1:15152293781:web:8a3988584c1de58d7a389c',
    messagingSenderId: '15152293781',
    projectId: 'local-shelf-98604',
    authDomain: 'local-shelf-98604.firebaseapp.com',
    databaseURL: 'https://local-shelf-98604-default-rtdb.firebaseio.com',
    storageBucket: 'local-shelf-98604.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDl0r_RmKSplKpC7kMoODqllH-0jHrrW98',
    appId: '1:15152293781:android:1beb28add3fbf8de7a389c',
    messagingSenderId: '15152293781',
    projectId: 'local-shelf-98604',
    databaseURL: 'https://local-shelf-98604-default-rtdb.firebaseio.com',
    storageBucket: 'local-shelf-98604.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCmtG44MhUMe1H05cNFIkKZMuX9kvILXWo',
    appId: '1:15152293781:ios:eb224b9d91cac3ad7a389c',
    messagingSenderId: '15152293781',
    projectId: 'local-shelf-98604',
    databaseURL: 'https://local-shelf-98604-default-rtdb.firebaseio.com',
    storageBucket: 'local-shelf-98604.firebasestorage.app',
    iosBundleId: 'com.example.localShelf',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCmtG44MhUMe1H05cNFIkKZMuX9kvILXWo',
    appId: '1:15152293781:ios:eb224b9d91cac3ad7a389c',
    messagingSenderId: '15152293781',
    projectId: 'local-shelf-98604',
    databaseURL: 'https://local-shelf-98604-default-rtdb.firebaseio.com',
    storageBucket: 'local-shelf-98604.firebasestorage.app',
    iosBundleId: 'com.example.localShelf',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyARltQLFudCyPx7gF5aez2n25nSaL-IBLs',
    appId: '1:15152293781:web:37e3715ed51487797a389c',
    messagingSenderId: '15152293781',
    projectId: 'local-shelf-98604',
    authDomain: 'local-shelf-98604.firebaseapp.com',
    databaseURL: 'https://local-shelf-98604-default-rtdb.firebaseio.com',
    storageBucket: 'local-shelf-98604.firebasestorage.app',
  );
}
